remote_theme: dieghernan/chulapa

# Find errors on this file with http://www.yamllint.com/

# Chulapa docs: https://dieghernan.github.io/chulapa/docs/02-config

# A. Site Settings /SEO options
# Overall options for your site, would affect your site SEO
# Default values are explained
locale                  :     #default["en-US"] format language-TERRITORY , e.g fr, en-GB, es-MX, pt-BR
title                   : Justin Lanjil    #default["repository_name"]
title_separator         :     #default [" | "]
subtitle                : Artist & Storyteller    #default [your-repository-tagline]  
description             : Collected works and creative blog. #default [your-repository-tagline]
url                     :     https://justinlanjil.art
baseurl                 :     #On Github Pages you may leave it blank. Have a look to: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
words_per_minute        :     #default[200]
timezone                :     #"Europe/Madrid ,see https://jekyllrb.com/docs/configuration/options/ and https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# SEO
og_image                :     #default[author.avatar (see below)] or [github-avatar]
twitter_site            :     #Avoid @
author:
  name                  :  Justin   # Name Surname Company
  avatar                :     # Try a square file. Info: Your github avatar on https://github.com/[USERNAME].png #should I use the skull here? I think so but do a new one!
  location              :  "Madrid, Spain"   # New York, USA 
#  links:                
#    - url:  #A link or email: https://twitter.com/jack, mail@example.com
#      icon: # A Fontawesome 5 code: fab fa-twitter - see https://fontawesome.com/
#    - url:  # Another link
#      icon: # Anothet FontAwesome code

fa_version: #default ["6"] Use 6 or 5
fa_kit_code: # Your FontAwesome kit code. If not provided a free hosted version (slower) will be loaded:  https://fontawesome.com/ 
fa_v4_support: #Bool Add FontAwesome 4 support 
# Web tracking - Google services https://analytics.google.com/analytics/web/
# gtag_id is the preferred option, see https://developers.google.com/analytics/devguides/collection/gtagjs/migration?hl=en
# analytics provided for backwards compatibility
gtag_id                 :  
analytics_id            :  

# Search providers
# Available free search engines:
# - lunr https://lunrjs.com/ 
# - algolia v4 https://www.algolia.com/ - needs further configuration
# - google custom search engine https://cse.google.es/ 
search:
  provider              : lunr #Select a provider for enable search: lunr, algolia, google
  label                 :  #default ["Search"] Text on navbar when search is enabled 
  landing_page          :  #default ["/search"] Link on navbar 
  lunr_maxwords         :  #default [30] lunr only - May slow down your site build
  algolia_logo          :  true #Displays algolia logo. Should be set to true if you are on a community plan, otherwise false.  

google_cse_id: #Your cse id
# This site uses jekyll-algolia plugin https://community.algolia.com/jekyll-algolia/
# Recommended additional configuration provided, could be modified. Add your own parameters
algolia:                                                                   
  application_id        : 
  index_name            : 
  search_only_api_key   : 
  files_to_exclude:         #Optional
    - _layouts/*.html
    - _includes/*.html
  extensions_to_index:      #Optional
    - html
    - md
  searchableAttributes:     #Optional                                                    
    - title                                                                    
    - headings                                                                 
    - unordered(content)                                                       
    - unordered(subtitle)                                                      
    - unordered(categories)                                                    
    - unordered(collection)                                                    
    - unordered(tags) 
  customRanking:            #Optional
    - desc(include_on_search)
    - desc(title)
    - desc(content) 
    - desc(subtitle)
    
comments:
  provider:         #Enable comments via Disqus, giscus or Cactus.chat
  disqus_shortname: #Your site id : check your address https://{{ disqus.shortname }}.disqus.com/admin/
  cactus_shortname: #Your site id as registered with Cactus.chat
  
# B. Navigation
# Configure your navbar and the footer of your site

# Navbar: 
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  style     :  #default is the classical top navbar, set "fab" for a floating action button navbar or "dual"
  expand    :  # At which device size expand the navbar menu. default[md] https://getbootstrap.com/docs/4.5/layout/overview/
  brand:
    title   :  " Justin Lanjil"
    subtitle: "Artist & Storyteller"
    url     :  # default["url/baseurl"]
    img     :  "./assets/img/brand_img/brand_logo_social_60x60.png"
  nav:
  - title   : Blog
    url     : /blog/
  - title: Games	
    child   :
    - title : Interactive fiction
      url   : /games/interactive-fiction
  - title: Stories	
    child   :
    - title : Standalone
      url   : /stories/standalone
    - title : Patron Saints
      url   : /stories/patron-saints
  - title : Current skin # keep this but add it to the git_ignore
    url   : /current-skin
#Social links to be placed on your site footer
footer:
  links:
    - label : Tumblr # Label
      icon  : fab fa-tumblr # Fontawesome 5 icon
      url   : https://www.tumblr.com/wickedliltongue # A link or email: https://twitter.com/jack, mail@example.com
    - label : Instagram
      icon  : fab fa-instagram
      url   : https://www.instagram.com/justinlart/
    - label : Itch
      icon  : fab fa-itch-io
      url   : https://wicked-little-tongue.itch.io/
    - label : Twitter
      icon  : fab fa-twitter
      url   : https://twitter.com/wickedliltongue
  copyright: © <year> Justin Lanjil 
  
# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts:
 # - url : # 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap'
  - url: https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap
  - url: https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap


# Theme and colors
chulapa-skin:
  # highlight     :  # default["default"]
  skin         :  lux # Optional predefined skins
  vars          :
    headings-font-family : "Montserrat, sans-serif"
    headings-font-weight : "600" #Semibold
    font-family-base : "Libre Baskerville, serif"
    # nav bar custom colors
    navbar-chulapa-bg-color : "#f6f6ee"
    navbar-chulapa-text-color : "#111109"
    navbar-chulapa-active-color: "#4d4d39"
    navbar-chulapa-hover-color : "#000"
    navbar-chulapa-disabled-color: "#babaab"
    # hamburger custom colors
    navbar-chulapa-toggler-color: "#111109"
    navbar-chulapa-toggler-color-bg: "#f6f6ee"
    # foot custom colors
    footer-chulapa-bg-color : "transparent"
    footer-chulapa-text-color : "#111109"
    footer-chulapa-hover-color : "#000"
    footer-chulapa-icon-color : "#111109"
    footer-chulapa-icon-hover-color : "#000"
    # to more easily change all of the white elements
    white: "#f6f6ee"
    gray-100 : "#f6f6ee"
    gray-200 : "#f4f4f1"
    gray-300 : "#ddddd5"
    gray-400 : "#babaab"
    gray-500 : "#70705C"
    gray-600 : "#4d4d39"
    gray-700 : "#444422"
    gray-800 : "#2A2A22"
    gray-900 : "#111109"
    blue : "#cc8800" # this doesn't work on the radio buttons? There's something weird there though.
    primary : "#babaab"
    secondary : "#4d4d39"
    success : "#888844"
    info : "#8c8c73"
    warning : "#cc8800"
    danger : "#99003d"
    light : "#f6f6ee"
    dark : "#111109"
    link-color : "#cc8800"
    # adjustments for primary color contrast (dark text)
    nav-pills-link-active-color: "#111109"
    list-group-active-color: "#111109"
    list-group-action-active-color: "#111109"
    # carousel colors
    carousel-control-color: "#111109"
    carousel-indicator-active-bg: "#111109"
    # icon hover
    footer-chulapa-icon-hover-color: "#babaab"


    
# D. Jekyll Defaults and collections: see https://jekyllrb.com/

# Blog pagination: on this site /blog/index.html. https://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: "/blog/page:num/"
paginator_maxnum: 3  #default[3] Custom: max of number to be displayed on the paginator

# Collections https://jekyllrb.com/docs/step-by-step/09-collections/
collections:
  cheatsheet:
    output: true
    permalink: /cheatsheets/:name
  pages:
    output: true
    permalink: /:path
  collected_works:
    output: false
  stories:
    output: true
  games:
    output: true
collections_dir     : 
permalink           : /:year:month:day_:title/


# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search   : false
      cloudtag_url        : /tags #This is where the link on tags would redirect
      cloudcategory_url   : /categories #This is where the link on categories would redirect
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_related      : false
      show_bottomnavs   : true
      show_sociallinks  : false
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_author       : false
      show_breadcrumb   : false
      breadcrumb_list   :
        - label: Blog
          url: /blog/
  -
    scope:
      path: ""
      type: "stories"
    values:
      layout: "short_story"
      header_type: "image"
      include_on_search   : true
      show_comments       : true
      show_tags           : false
      show_categories     : false
  -
    scope:
      path: ""
      type: "games"
    values:
      layout: "default"
      header_type: "hero"
      include_on_search   : true
      show_comments       : true
      show_tags           : false
      show_categories     : false
      play_url_text       : "play on itch.io "
  -
    scope:
      path: ""
      type: "cheatsheet"
    values:
      header_type       : "hero"
      show_bottomnavs   : true
      show_sociallinks  : true
      include_on_search : true
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Cheatsheets
          url: /cheatsheets
  -
    scope:
      path: "assets/img/gallery"
    values:
      image_col         : gallery
  -
    scope:
      path: "assets/img/placeholder"
    values:
      image_col         : placeholder


# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap


# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

